// This file is generated by scripts/generate-env-config.js
// Do not edit this file directly.

const envConfig = {
  NODE_ENV: process.env.NODE_ENV || 'development',
  NEXT_PORT: process.env.NEXT_PORT || '3000',
  NEXT_HOST: process.env.NEXT_HOST || 'localhost',
  API_PORT: process.env.API_PORT || '8000',
  API_HOST: process.env.API_HOST || '0.0.0.0',
  PYTHON_PATH: process.env.PYTHON_PATH || 'python3',
  VENV_PATH: process.env.VENV_PATH || './ai/venv',
  DATABASE_URL: process.env.DATABASE_URL || '',
  DATABASE_TYPE: process.env.DATABASE_TYPE || 'postgresql',
  LOG_LEVEL: process.env.LOG_LEVEL || 'INFO',
  ENABLE_AI_TRAINING: process.env.ENABLE_AI_TRAINING === 'true',
};

export const config = envConfig;
export default envConfig;
