#!/bin/bash

# Clerk Setup Script for MidoHub
# This script helps you set up Clerk authentication

echo "🚀 Welcome to MidoHub Clerk Setup!"
echo "=================================="
echo ""

# Check if .env.local exists
if [ -f ".env.local" ]; then
    echo "📁 Found existing .env.local file"
    echo "   Backing up to .env.local.backup"
    cp .env.local .env.local.backup
else
    echo "📁 Creating new .env.local file"
fi

echo ""
echo "🔑 To complete setup, you need to:"
echo "   1. Go to https://clerk.com and create an account"
echo "   2. Create a new application"
echo "   3. Choose Next.js as your framework"
echo "   4. Copy your publishable key and secret key"
echo ""

# Prompt for Clerk keys
read -p "Enter your Clerk Publishable Key (pk_test_...): " CLERK_PUBLISHABLE_KEY
read -p "Enter your Clerk Secret Key (sk_test_...): " CLERK_SECRET_KEY

# Validate keys
if [[ $CLERK_PUBLISHABLE_KEY != pk_test_* ]] && [[ $CLERK_PUBLISHABLE_KEY != pk_live_* ]]; then
    echo "❌ Invalid publishable key format. Should start with pk_test_ or pk_live_"
    exit 1
fi

if [[ $CLERK_SECRET_KEY != sk_test_* ]] && [[ $CLERK_SECRET_KEY != sk_live_* ]]; then
    echo "❌ Invalid secret key format. Should start with sk_test_ or sk_live_"
    exit 1
fi

echo ""
echo "✅ Keys validated successfully!"
echo ""

# Create .env.local file
cat > .env.local << EOF
# Clerk Authentication Configuration
# Generated by setup-clerk.sh
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$CLERK_PUBLISHABLE_KEY
CLERK_SECRET_KEY=$CLERK_SECRET_KEY

# Clerk URLs
NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/dashboard
NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/dashboard
NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL=/
NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL=/

# Netlify Configuration
NEXT_PUBLIC_NETLIFY_SITE_URL=https://midostore.netlify.app

# Database Configuration
DATABASE_URL=your_database_url_here

# API Keys
STRIPE_SECRET_KEY=your_stripe_secret_key_here
STRIPE_PUBLISHABLE_KEY=your_stripe_publishable_key_here

# Exchange Rate API
EXCHANGE_RATE_API_KEY=your_exchange_rate_api_key
EXCHANGE_RATE_API_BASE_URL=https://api.exchangerate-api.com/v4

# Alibaba/AliExpress API Configuration
ALIBABA_API_BASE_URL=https://api.alibaba.com
ALIBABA_API_KEY=your_alibaba_api_key

# Prisma Engine Configuration (for NixOS compatibility)
PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1

# AI Location-Based Search Configuration
NEXT_PUBLIC_WEATHER_API_KEY=your_openweathermap_api_key
IP_API_KEY=your_ip_api_key

# SimpleAnalytics Configuration
NEXT_PUBLIC_SIMPLEANALYTICS_DOMAIN=your_domain.com
SIMPLEANALYTICS_API_KEY=your_simpleanalytics_api_key
SIMPLEANALYTICS_API_URL=https://api.simpleanalytics.com
EOF

echo "✅ .env.local file created successfully!"
echo ""
echo "🔄 Next steps:"
echo "   1. Restart your development server (npm run dev)"
echo "   2. Test authentication at /sign-in and /sign-up"
echo "   3. Check the browser console for any warnings"
echo ""
echo "📚 For more help, see CLERK_SETUP_GUIDE.md"
echo ""
echo "🎉 Setup complete! Happy coding!"